### ISSUE TITLE
Raster image data API

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#17]
The current raster API is proving to be a little difficult to work with, both because I have to load data into memory then save it to temporary files after modifying it and because the results are incorrect (reduced/wrong colors). I want to get you a more specific bug report for the color problems importing jpeg and png images, but I also want to add a raster data api which would insert the raster bytes prep-prepared, converted to the right icc profile on the python side and coded into the jpeg or pdf bitmap formats.

Would you have any objections to this API addition?

**Comment by jpakkane** [comment]
This is definitely something we need. In fact if you look at the color management bug, it specifically lists this as something that is required. Here are some things that the API should provice

- Adding raster images in Device{RGB, Gray, CMYK}
- With or without alpha channel
- Adding image data that is in a given ICC profile color
- 8 bits per color component and alpha, DeviceGRAY can be 1 bit, possibility of adding 16 bit support later
- Data passed in can be either uncompressed or zlib compressed, with possibility to support other compression schemes later
- Color conversion if needed, e.g. sRGB to DeviceCMYK
- Specifying all color conversion parameters like rendering intent
- If global color conversion strategy (not implemented yet) says not to convert, error out instead

Feel free to add your own.

This is quite complex so the API probably needs to do something like this:

```
CapyRasterImageOptions *iopt;
// allocate here
set_pixel_data(iopt, buffer, buffer_size);
// set other parameters here
capy_generator_add_raster_image(iopt);
// deallocate
```

> because the results are incorrect (reduced/wrong colors).

This should never be happening. If you import an RGB PNG and output device colorspace is RGB, every color value should pass through unaltered. Anything else is a bug. The only loss of color should come from either color space conversions or JPG lossy compression.

I have a vague recollection that some apps produce PNGs and/or JPGs that have known wrong color profiles attached.

**Comment by jpakkane** [comment]
The API now exists so closing. Improvements to it can be done in other issues or PRs.
