### ISSUE TITLE
Color management open policy questions

### ISSUE THREAD

**Issue by jpakkane** [jpakkane/capypdf#2]
Or in other words "when and how should color conversions happen"? There are many different, and totally reasonable, ways of doing this. Such as:

- Pass all colors through without conversions
- Convert everything silently to target colorspace
- Error out if trying to specify a color that is not in the output colorspace
- Same as above but also permit ICC and L*a*b* colors

As an example suppose you call `cmd_rg` while creating a PDF/X3 CMYK output file:

- writing an `rg` command in the stream must not happen as it would create an invalid PDF
- converting to device cmyk is _probably_ what the user wants and doing the conversion ourselves is convenient for users, because then they don't need to do it
- on the other hand in some programs it would be considered an error if they ever try to set an RGB color and thus would probably want an error rather than a silent conversion

There are more complicated cases to consider as well. Suppose you load an RGB image when generating a PDF/X3 file. Then you'd probably want to express the rendering intent to use for the conversion. Currently you can't.

**Comment by jpakkane** [comment]
Thinking a bit more:

- `cmd_rg` et al should probably not do color conversions, either they write the command as is or error out
- `Color` based APIs could do color conversion (if permitted by the user)
- there should probably be a function like `convert_color(FromColorObject, ToColorObject, format_specification)` so people can do color conversions by hand

**Comment by doctormo** [comment]
For inkscape I'll probably be requiring all vector colors to be in the deviceCMYK profile space, but I will do user testing to figure out what users actually want to see (i.e. errors, visual indications, etc)

For raster images I intend to do an automatic conversion, since raster pixel conversions are well understood and non-sRGB rasters aren't allowed in SVG, so they're always going to be passed in as sRGB and will need converting to the deviceCMYK space.

**Comment by jpakkane** [comment]
> they're always going to be passed in as sRGB and will need converting to the deviceCMYK space.

I'm guessing we need to have a function something like:

```
EC add_image_from_data(const char *pixels, int32_t bufsize, 
  const char *alphachannel, int32 alphasize, 
  const char *icc_profile, int32 icc_size,
  imageFormat,
  const  iopts *extras); // for overriding rendering intent, specifying that the data is already zlib compressed etc
```

At the moment PDF only does 8-bit graphics, but FWICT there are plans to add HDR image support at some point.

**Comment by jpakkane** [comment]
The code has drifted towards not doing any color conversions implicitly. It is up to the user to invoke said conversions, we only check that they are used correctly (i.e. not using rgb images in PDF/X3 etc).
