### ISSUE TITLE
Library wheel requires Gtk4

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#25]
When building the latest capypdf wheel, the mason build requires Gtk4 despite not needing any gtk4 for just the libraries.

I'm actually concerned about how pdfviewer et al aren't separated in the codebase, should we split them out into their own repositories and use a submodule so there's less possible confusion between the library and the applications that use it?

In Inkscape we do this for things like lib2geom which are still in-line, but use git submodules so they can have their own development life cycle and much fewer dependencies.

**Comment by jpakkane** [comment]
It should not "require" it as such. If GTK 4 is available it will build the devtool and if it is not, then it won't.

I this causes problems then I guess we can move devtools in a separate directory and add a build option whether to build devtools or not.

**Comment by doctormo** [comment]
There is a compatibility problem with older glibs and newer Gtk4's, I have PopOS based on Ubuntu 22.04, and have been doing gtk4 work with Inkscape so it's installed. Running ninja on the builddir causes a single `G_APPLICATION_DEFAULT_FLAGS` isn't defined error.

But this would happen if I wanted the gtk programs anyway. The real grumble is that I don't need the gtk programs.

**Comment by jpakkane** [comment]
Devtools should now be separated and only built if you explicitly configure them to.

**Comment by jpakkane** [comment]
GTK is no longer looked unless you expliclly ask for it so closing.

**Comment by doctormo** [comment]
Thanks Jussi :heart:
