### ISSUE TITLE
Colors and converting automatically

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#44]
I see that the `set_color` function is the intended API use, but this doesn't work for flat colors since it crashes looking for icc profiles.

I presume this can be avoided if the color space is set for the transparency group, or document. Though there's no way to load memory icc profiles yet and I really really don't want capypdf to be converting colors for me, I would much rather it error out and I'd certainly prefer an error to a crash.

Can you guide on what the set_color is suppose to be doing for the API user and what is out of step?

**Comment by jpakkane** [comment]
There is no `set_color` function in the public api? What specifically do you mean? `set_{non}stroke` or something else?

If there is a crash for those, then it seems like a bug. `set_{non}stroke` should not do any color conversions, it should use the color object as is and just serialize it out. That is, if you have set it to devicecmyk, it should write out `c m y k {k/K}` and nothing else. It should only look up ICC profiles if you have set the Color object to have an ICC value.

**Comment by doctormo** [comment]
For the record this is the traceback:

```
0# Inkscape::Application::crash_handler(int) at /home/doctormo/Projects/inkscape/inkscape/src/inkscape.cpp:562
 1# 0x00007BF7CA845320 in /lib/x86_64-linux-gnu/libc.so.6
 2# cmsDoTransform in /lib/x86_64-linux-gnu/liblcms2.so.2
 3# capypdf::internal::PdfColorConverter::to_rgb(capypdf::internal::DeviceCMYKColor const&) at ../src/colorconverter.cpp:160
 4# capypdf::internal::PdfDrawContext::set_color(capypdf::internal::DeviceCMYKColor const&, bool) at ../src/drawcontext.cpp:666
 5# capypdf::internal::PdfDrawContext::set_color(std::variant<capypdf::internal::DeviceRGBColor, capypdf::internal::DeviceGrayColor, capypdf::internal::DeviceCMYKColor, capypdf::internal::ICCColor, capypdf::internal::LabColor, capypdf::internal::SeparationColor, CapyPDF_PatternId> const&, bool) at ../src/drawcontext.cpp:615
 6# capypdf::internal::PdfDrawContext::set_nonstroke_color(std::variant<capypdf::internal::DeviceRGBColor, capypdf::internal::DeviceGrayColor, capypdf::internal::DeviceCMYKColor, capypdf::internal::ICCColor, capypdf::internal::LabColor, capypdf::internal::SeparationColor, CapyPDF_PatternId> const&) at ../src/drawcontext.hpp:175
 7# capy_dc_set_nonstroke at ../src/capi.cpp:808
 8# capypdf::DrawContext::set_nonstroke(capypdf::Color&) at /home/doctormo/.build/inkscape/deps/include/capypdf-0/capypdf.hpp:374
```

The code is simply

```
capypdf::Color out;
out.set_cmyk(c, m, y, k);
_ctx.set_nonstroke(out);
```

No deviceCMYK profile is set in the document metadata.

**Comment by doctormo** [comment]
The code in drawcontext checks `doc->opts.output_colorspace` pretty deliberately. When you said `if you have set it` by **it** did you mean **the document**? Because this is exactly what I don't want capypdf doing. I don't need it trying to protect me from writing an rgb color into a CMYK document and visa versa.
