### ISSUE TITLE
Raster images can't be loaded from data

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#52]
Because SVGs mostly contain base64 encoded raster images; image data needs to be fed into capypdf as data and not as a filename.

The current code is extremely convoluted and I don't think is amenable to being changed into accepting data instead of filenames.

Do we need new functionality to handle image data?

**Comment by doctormo** [comment]
OK, so the process here would be...

Read base64 encoded PNG, decode the PNG into pixel data, compress that data with zlib, send that pixel data to capypdf? So it ends up in the pdf as a BMP?

What happens if it's a Jpeg? Do we end up double encoding it? What if it's a CMYK jpeg, does the pixel data support 4, 5 channels with or without transparencies in the PNG streams?

The data in an SVG is literally the PNG, JPEG or TIFF *file data*, not pixel data. Though I can decode and re-encode, I just think we'll lose a lot of consistency when doing that.

**Comment by doctormo** [comment]
OK looking deeper at the structures, it looks like png and tiff data would be handled as raw pixels and jpegs would be embedded as jpeg streams?

**Comment by jpakkane** [comment]
Passing in png files directly is not supported ATM. We should do that. I did the current implementation first, because I assumed that most people already have the pixel data in memory for display purposes.

> does the pixel data support 4, 5 channels with or without transparencies in the PNG streams?

All of that _should_ be supported eventually. Currently it is not.

> Read base64 encoded PNG, decode the PNG into pixel data, compress that data with zlib, send that pixel data to capypdf? 

You don't have to compress it, CapyPDF does it automatically. That was more of if you already have it in zlib compressed form or want to compress it yourself for whatever reason (i.e. running a custom zlib encoder and/or doing all the compression beforehand in parallel).

**Comment by doctormo** [comment]
The problem with using display data is that it's not guaranteed to be in the right color space. Cairo pixbufs will negate CMYK data for example, let alone other RGB icc profiles.

What I'm hoping for is being able to get whatever is in the SVG, into the PDF file with only syntactical conversions. The goal is to do conversions like color, raster formats, filters, fonts etc in the GUI, inside SVG before we even get to PDF.

The raster API looks to be a bit messy, should I start thinking of a new way of providing data as PNG, JPEG and TIFF streams directly?

**Comment by jpakkane** [comment]
I just pushed some refactoring work on this. You might want to look at that first. It should be a case of adding a new function like "load_image_from_memory" and making it call the corresponding function in `imagefileops.cpp`.

Note that I have not actually tested if those code paths work (nor have I formally proven them correct).
