### ISSUE TITLE
Downstream Report

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#59]
This is a video that goes through where we are in the Inkscape use of capypdf.

https://youtu.be/iEp-ydPy2EA

Close this when seen.

**Comment by jpakkane** [comment]
Yep, did see. Good stuff. Just a note, CapyPDF _should_ read ICC profiles from TIFF files but it does not yet do that for PNG images. Apparently it can not be done with the simple API I have been using thus far so it needs to be changed.

**Comment by doctormo** [comment]
Ah, whatever type of tiff file I have in my tests is currently failing. Both CMYK jpeg and ICC Tiff don't load.
