### ISSUE TITLE
Inconsistant context API for fill and stroke

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#6]
When setting the fill and stroke, we have different names for the functions used to set shape and text fill and strokes:

```
shape_ctx.set_nonstroke(fill)
text_ctx.nonstroke_color(fill)
```

These kinds of functions should be harmonised, as much as possible.

**Comment by jpakkane** [comment]
Yes. I have tried to do this already, but sometimes things fall through cracks.
