### ISSUE TITLE
Error in libpng opening png file

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#62]
I'm currently getting the fatal, non-catchable error from libpng: `libpng error: Not a PNG file`

It looks like any tiff or jpeg image will cause this error as it's just pushing those bytes through libpng to see if it'll work; but it fails hard.

traceback:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff3e4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff3e288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff320251a in ??? () at /lib/x86_64-linux-gnu/libpng16.so.16
#6  0x00007ffff3204654 in png_error () at /lib/x86_64-linux-gnu/libpng16.so.16
#7  0x00007ffff320a58f in png_read_info () at /lib/x86_64-linux-gnu/libpng16.so.16
#8  0x00007ffff320ec1f in png_read_png () at /lib/x86_64-linux-gnu/libpng16.so.16
#9  0x00007ffff390c660 in capypdf::internal::(anonymous namespace)::load_png_file (f=0x555555afb990) at ../src/imagefileops.cpp:425
#10 0x00007ffff390c7ad in capypdf::internal::(anonymous namespace)::load_png_file (fname=filesystem::path "/tmp/ink_raster_jpeg_XXXXXX6C9WY2" = {...})
    at ../src/imagefileops.cpp:435
#11 0x00007ffff390d8f5 in capypdf::internal::load_image_file (fname=filesystem::path "/tmp/ink_raster_jpeg_XXXXXX6C9WY2" = {...})
    at ../src/imagefileops.cpp:575
#12 0x00007ffff3877a92 in capypdf::internal::PdfGen::load_image (this=0x555556660d10, fname=filesystem::path "/tmp/ink_raster_jpeg_XXXXXX6C9WY2" = {...})
    at ../src/generator.cpp:66
#13 0x00007ffff3937084 in capy_generator_load_image (gen=0x555556660d10, fname=0x555556661620 "/tmp/ink_raster_jpeg_XXXXXX6C9WY2", out_ptr=0x7fffffffc370)
    at ../src/capi.cpp:330
#14 0x00007ffff6b13f6a in capypdf::Generator::load_image (this=this@entry=0x7fffffffc9b0, fname=<optimized out>)
    at /home/doctormo/.build/inkscape/deps/include/capypdf-0/capypdf.hpp:669
#15 0x00007ffff6b1364e in Inkscape::Extension::Internal::PdfBuilder::Document::load_image
```

**Comment by jpakkane** [comment]
I made a quick fix to use setjmp/longjmp. If this fixes it for you feel free to close the issue, otherwise post whatever is the new error message it prints ous.

**Comment by doctormo** [comment]
The error has changed, but there is still a crash:

# Before

 *  sRGB Jpeg - Crash
 * CMYK jpeg - Crash
 * Icc Tiff - Crash
 * sRGB PNG - Works

# After

 *  sRGB Jpeg - Works
 * CMYK jpeg - Blank, but no crash
 * Icc Tiff - Crash (see below)
 * sRGB PNG - Works


```
libpng error: Not a PNG file
libpng error: Not a PNG file
Unsupported image file format: /tmp/ink_raster_jpeg_XXXXXXSV74Y2

** (org.inkscape.Inkscape:654299): WARNING **: 13:58:10.489: Could not add image to PDF: Failed to load data from file.
libpng error: Not a PNG file
Segmentation fault (core dumped)
```

```
(gdb) 
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:147
#1  0x041e69afe4b9d070 in ??? ()
```

**Comment by jpakkane** [comment]
Could you post just the unaltered TIFF file?

**Comment by jpakkane** [comment]
Actually never mind, should be fixed now.

**Comment by doctormo** [comment]
Confirmed working. I'll close this one. Want me to make a fresh report with the unsupported files attached?

**Comment by jpakkane** [comment]
Is it something else than CMYK jpegs? Because [those are jank](https://nibblestew.blogspot.com/2024/12/cmyk-me-baby-one-more-time.html) and I don't really know why.

**Comment by doctormo** [comment]
The tiff with an icc: 
[image.zip](https://github.com/user-attachments/files/18157639/image.zip)

**Comment by doctormo** [comment]
For cmp, this is the CMYK jpeg 
![image-cmyk](https://github.com/user-attachments/assets/373d7ee2-e157-4e75-8c4f-827483cb04e9)

One thing I had thought was that the jpegs might be getting broken by the PDF's own lack of profile information. The output from scribus tends to make a cmyk profile with a flat definition in the header, but capypdf wouldn't do that when I tried.

**Comment by jpakkane** [comment]
That was the case, but I changed it recently so the internal icc profile is extracted and used in PDF. In my testing Scribus converted cmyk jpegs into three channel ICC RGB jpegs. Which is not efficient as that has to re-encode the entire image.

**Comment by doctormo** [comment]
At least in that case it's theoretically possible to get the CMYK values back out at print time, by using the same lossless rendering intent (assuming the RGB gamut is bigger, which it usually is) and that's fine for *photographs* and things like that. But I bet a lot of folks would be surprised they loose control over the black channel if it's a logo or something else like that.

**Comment by jpakkane** [comment]
[It turns out things are complicated and broken due to legacy reasons](https://graphicdesign.stackexchange.com/questions/12894/cmyk-jpegs-extracted-from-pdf-appear-inverted).

I made the code invert all CMYK channels and it worked with all test images I had available.

**Comment by doctormo** [comment]
![image](https://github.com/user-attachments/assets/09e46f3d-0ed3-47a8-bf5a-668f334a16d0)

Thanks. That is a 100% success, at least on my tests. Likely I will expand these tests as user errors come in. One of the main goals I have to think about is how conversion of filters will work, since converting them to CMYK rasters will require *rendering* them out in CMYK channels, something inkscape (cairo) can't do yet. At least I'll know that it's not the raster format itself that's the cause of any difficulty!
